version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app  # Mount backend code for hot reload
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Enables FastAPI live reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # Use dev Dockerfile
    volumes:
      - ./frontend:/app  # Mount frontend code for hot reload
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures Vue hot reload works in Docker
    command: npm run dev  # Runs Vite dev server

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizzastore
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: