version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app # Mount backend code for hot reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/.env

  db:
    build: ./db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pizzastore
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: